### ISSUE TITLE
not enough arguments for format string

### ISSUE THREAD

**Issue by orel35** [rbignon/doctoshotgun#13]
Hello,
merci pour le script franchement. En revanche, j'ai un soucis, au moment de trouver un créneau, ça me renvoit "not enough arguments for format string".
Précision je suis sous Windows 10 avec Python 3.9
![bug-doctoshotgun](https://user-images.githubusercontent.com/84409376/118763596-6715cb80-b878-11eb-8dee-9a9c9cf0854d.jpg)
Merci

**Comment by rbignon** [comment]
Bonjour,

Effectivement il y avait un bug sur la fonction de logs depuis hier soir, il devrait être corrigé.

Pouvez-vous réessayer et confirmer que ça fonctionne correctement ?

Merci.
