### ISSUE TITLE
missing city if both motive_ids 6970 and 7005

### ISSUE THREAD

**Issue by MyLordAngus** [rbignon/doctoshotgun#14]
Bonjour,

Tout d'abord un grand merci pour ton script,

J'ai essayé de booker un créneau pour Puteaux mais j'ai l'impression que le script n'obtient jamais le centre de la ville dans ses résultats de recherches, alors que je le vois en tête des résultats sur l'url de mon navigateur : 
https://www.doctolib.fr/vaccination-covid-19/puteaux?ref_visit_motive_ids[]=6970&ref_visit_motive_ids[]=7005

Et là plus étonnant, si j'inverse les ids 6970/7005 de la première requête de la méthode find_centers, le cabinet est trouvé (Trying to find a slot in Centre de Vaccination Covid-19 de Puteaux).

Je ne sais pas si je suis très clair, et je ne suis pas très bon en Python, mais peut être qu'il y a une explication derrière...

**Comment by MyLordAngus** [comment]
Juste un diff pour expliciter un peu sur la modif que j'ai faite.

```
-        self.centers.go(where=where, params={'ref_visit_motive_ids[]': '6970', 'ref_visit_motive_ids[]': '7005'})                                         
+        self.centers.go(where=where, params={'ref_visit_motive_ids[]': '7005', 'ref_visit_motive_ids[]': '6970'})
```

**Comment by Dettorer** [comment]
Oui vu que c'est un dictionnaire et que les clés sont les mêmes, seule la dernière occurrence est gardée, idem [ligne 188](https://github.com/rbignon/doctoshotgun/blob/master/doctoshotgun.py#L188).

**Comment by nicogodet** [comment]
Remplacer par `'ref_visit_motive_ids[]': '6970,7005'` ?
Comme ça a été fait dans https://github.com/anto35/doctoshotgun/blob/master/doctoshotgun.py#L192

**Comment by Dettorer** [comment]
Ça a l'air de marcher ! Je fais une PR.

**Comment by MyLordAngus** [comment]
Vous êtes certains que ça résoud le bug de la bonne manière ? Car quand j'inverse les 2 paramètres en mettant en premier l'id 7005 ('7005,6970'), je n'ai pas de proposition à nouveau.

**Comment by MyLordAngus** [comment]
D'ailleurs l'url suivante me retourne le centre de Puteaux en premier (c'est cette url qui est interrogée avec la PR) : 
https://www.doctolib.fr/vaccination-covid-19/puteaux?ref_visit_motive_ids[]=6970,7005

Par contre pas de Puteaux ici :
https://www.doctolib.fr/vaccination-covid-19/puteaux?ref_visit_motive_ids[]=6970,7005

Du coup je suis partagé sur la solution. En fait, il faudrait bien utiliser une URL de la forme suivante : https://www.doctolib.fr/vaccination-covid-19/puteaux?ref_visit_motive_ids[]=7005&ref_visit_motive_ids[]=6970

car là même en inversant l'ordre des ids le résultat est identique.

**Comment by Dettorer** [comment]
Ah, my bad, j'ai testé trop rapidement. Je ne connais pas woob et avec un rapide coup d'œil dans la doc je n'ai pas trouvé d'interface pour ajouter des paramètres à une URL autrement qu'avec un dictionnaire (mais je n'ai pas tout regardé).

**Comment by Dettorer** [comment]
Ça veut probablement dire que https://github.com/anto35/doctoshotgun/blob/master/doctoshotgun.py#L192 est aussi un bug du coup.

**Comment by MyLordAngus** [comment]
J'ai l'impression d'avoir trouvé la notation qui fonctionne : 
`self.centers.go(where=where, params={'ref_visit_motive_ids[]': ['7005', '6970']})`

en regardant le lien suivant : https://stackoverflow.com/questions/27116424/handling-duplicate-keys-in-http-post-in-order-to-specify-multiple-values#27118320

En tout cas encore merci pour le script il m'a permis d'obtenir un rendez-vous malgré ce petit soucis :)

**Comment by Dettorer** [comment]
Ah oui effectivement cette fois ça a l'air de marcher, j'ai bien trois ensembles de centres différents avec `['7005', '6970']` vs `['7005']` vs `['6970']`, et j'ai bien les même centres si j'inverse l'ordre de la liste. Je réouvre ma PR.
