### ISSUE TITLE
Format des disponibilités

### ISSUE THREAD

**Issue by seranpion** [rbignon/doctoshotgun#27]
Dans certains cas le format des créneaux de disponibilité n'est pas celui attendu.

```python
self.doc['availabilities']['slots'][-1]
```
n'est pas un dictionnaire mais une chaîne de caractère.
Par exemple, un élément de availabilities peut avoir ce contenu:
```
{'date': '2021-05-22', 'slots': ['2021-05-22T09:30:00.000+02:00'], 'substitution': None}
```

**Comment by rbignon** [comment]
Avec ce contenu, ```self.doc['availabilities']['slots'][-1]``` fonctionne, non ?

**Comment by seranpion** [comment]
Oui, mais c'est alors une chaîne de caractères.
Le code en aval (dans la méthode `try_to_book_place`) s'attend à ce que ce soit un dictionnaire.
Il y cherche les clés `start_date` et `steps`.

J'ai ajouté une vérification dans ma PR #30 pour ne pas causer une exception.
Mais je ne suis pas allé jusqu'à voir comment rattraper la situation.

**Comment by rbignon** [comment]
Ah oui je comprends. Ok, du coup on peut considérer qu'avec la vérification que tu fais l'issue est close ? Note que ça doit être assez rare je ne l'ai jamais rencontré.

**Comment by seranpion** [comment]
Cette situation a été rare pour moi. Si la situation changera on pourra aviser.
On peut close cette discussion.
