### ISSUE TITLE
No third shot vaccinations in this country

### ISSUE THREAD

**Issue by skiwlkr** [rbignon/doctoshotgun#290]
Hey,
great repo!

I tried to book a third shot with it but always get the error that there is no third shot available in germany/berlin.
Is repo outdated or am I doing something wrong?

Cheers!

**Comment by nicolaus-hee** [comment]
Hi, please check:
Duplicate of #82
Addressed in PRs #287, #288, #289

**Comment by skiwlkr** [comment]
stupid me.
thanks
