### ISSUE TITLE
Will the script work with the new Doctolib queuing system?

### ISSUE THREAD

**Issue by zaccharieramzi** [rbignon/doctoshotgun#292]
Currently when I run the script I have the following message on loop:

```
This may take a few minutes/hours, be patient!
[2021-11-25 18:44:35]
No free slots found at selected centers. Trying another round in 5 sec...
[2021-11-25 18:44:40]
No free slots found at selected centers. Trying another round in 5 sec...
[2021-11-25 18:44:45]
No free slots found at selected centers. Trying another round in 5 sec...

...
```

I tried debugging, and saw that the url being requested ends up on a queuing system.

![image](https://user-images.githubusercontent.com/6387497/143485315-ca65e619-1236-40f2-92ce-2bfcf125954f.png)

I guess that if we keep pinging this url, it will always fall back at the back of the queue. 

Maybe fortunately with the new queuing system this script is not needed anymore, let's see.

**Comment by hadware** [comment]
Could there be a way of bypassing the queuing system?

**Comment by skiwlkr** [comment]
Same here for the german doctolib.

**Comment by zaccharieramzi** [comment]
I ended up being patient and using the official queuing system.

**Comment by Maxou44** [comment]
The script stucks with the new queue system, the queue use a cookie, it could be nice to resend the cookie each time we redo a request to progress in the queue

**Comment by rbignon** [comment]
Hello,

I'm looking how it works and patch doctolib soon to handle the queuing system.

**Comment by rbignon** [comment]
Ok the queue is now correctly handled. However, I think there are perhaps problems with support of 3rd shot, I'll do some tests later.

**Comment by skiwlkr** [comment]
Cool! Thanks!
I just tried it and it worked for 5 minutes and after that went back to the state like in the first post.
I kept it running and after another 10 minutes it got back to working correctly. 


It keeps jumping between those two states, but in the end it works and booked an appointment. Thanks!

**Comment by hadware** [comment]
Worked perfectly for me!
