### ISSUE TITLE
CloudFlare blocking request macOS 10.13.3

### ISSUE THREAD

**Issue by flnt** [rbignon/doctoshotgun#299]
Hi,

Thank you for the very nice script! 
This issue is not specific to doctoshotgun but maybe you can help, when running the code I get this error :

> Request blocked by CloudFlare

I understand that cloudscraper should bypass this anti-bot security but it is not the case.
Do you have any pointers/ideas on how to solve my issue ?

Thanks! 

Python 3.9.5
macOS 10.13.3 (High Sierra)

**Comment by jensMF** [comment]
Just retry until it works. Look at #56
