### ISSUE TITLE
('404 Client Error: Not Found',) always occurs when booking for the shot

### ISSUE THREAD

**Issue by fthorey** [rbignon/doctoshotgun#301]
I built the docker image on the latest commit on master

**Comment by agramfort** [comment]
I have the same issue

**Comment by agramfort** [comment]
it worked now for me.

**Comment by fthorey** [comment]
I guess this is because I had already on appointment scheduled

**Comment by froth-synthesio** [comment]
I have still have the same issue every time a slot is found. Did you do something to overcome this ?
