### ISSUE TITLE
OBTENIR UNE ERREUR WRONG LOGIN / PASSWORD AVEC UN MOT DE PASSE CORRECT

### ISSUE THREAD

**Issue by martor26** [rbignon/doctoshotgun#32]
Hi! I am executing the following command on CMD:/Salut! J'exécute la commande suivante sur CMD:

C:\Users\username>python doctoshotgun.py paris xx@gmail.com

and i get back Password: /et je récupère le mot de passe:

i can't see what i am typing but i keep on getting wrong login/password even if i input the right password/Je ne vois pas ce que je tape mais je continue à me tromper de login / mot de passe même si j'entre le bon mot de passe

Would you know how to fix this? Sauriez-vous comment résoudre ce problème?

thx a lot in advance!

**Comment by clemux** [comment]
Could you add the debug option and paste the result here?

-> `python doctoshotgun.py -d paris xx@gmail.com`

**Comment by martor26** [comment]
Hi! it worked once but then it stopped and when i tried again it didnt work. 
here is what i get from the debug: 
Password:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.doctolib.fr:443
DEBUG:urllib3.connectionpool:https://www.doctolib.fr:443 "GET /sessions/new HTTP/1.1" 200 None
INFO:browser:Response saved to f42a751b73514f9cbed79905e5a2c475
DEBUG:browser:Unable to handle https://www.doctolib.fr/sessions/new
DEBUG:urllib3.connectionpool:https://www.doctolib.fr:443 "POST /login.json HTTP/1.1" 401 None
INFO:browser:Response saved to a366fa1d482e4e0a89f2c1f2453fb21b
Wrong login/password

thanks a lot!
Martina

**Comment by martor26** [comment]
i am closing this as it worked again. It seems that it's only working if i enter the password very quickly!
thanks a lot for your help!
