### ISSUE TITLE
Semble non compatible avec windows

### ISSUE THREAD

**Issue by nono-london** [rbignon/doctoshotgun#35]
Lorsque je lance: "doctoshotgun.py paris username_email" de mon environemment venv, j'obtiens l'erreur suivante: 
"    from dateutil.parser import parse as parse_date
ModuleNotFoundError: No module named 'dateutil'
"
si je lance la commande du "./doctoshotgun.py paris username_email", l'erreur est:
"'.' is not recognized as an internal or external command,
operable program or batch file.
"
Comment faire fonctionner ce programme sous windows?
Merci

**Comment by clemux** [comment]
Il manque probablement l'installation des dépendances : `pip install -r requirements.txt`

**Comment by nono-london** [comment]
Non tout est installé  (j'ai refais tourner par acquis de conscience). A mon avis plus un problème de PYTHONPATH.

**Comment by clemux** [comment]
> si je lance la commande du "./doctoshotgun.py paris username_email", l'erreur est:
> "'.' is not recognized as an internal or external command,
> operable program or batch file.
> "

-> la syntaxe `./` n' est pas reconnue par windows, c'est normal.

Que dit `pip list` ?

En tout cas je peux confirmer que le programme fonctionne sous windows dans un venv.

**Comment by nono-london** [comment]
je suis dans un venv donc étonnat.
pip list:

(.venv) D:\path_to_project\doctoshotgun>pip list
Package            Version
------------------ ---------
atomicwrites       1.4.0
attrs              21.2.0
Babel              2.9.1
certifi            2020.12.5
chardet            4.0.0
cloudscraper       1.2.58
colorama           0.4.4
cssselect          1.1.0
html2text          2020.1.16
idna               2.10
importlib-metadata 4.0.1
iniconfig          1.1.1
lxml               4.6.3
packaging          20.9
Pillow             8.2.0
pip                21.1.1
pluggy             0.13.1
py                 1.10.0
pyparsing          2.4.7
pytest             6.2.4
python-dateutil    2.8.1
pytz               2021.1
PyYAML             5.4.1
requests           2.25.1
requests-toolbelt  0.9.1
responses          0.13.3
setuptools         56.2.0
six                1.16.0
termcolor          1.1.0
toml               0.10.2
typing-extensions  3.10.0.0
Unidecode          1.2.0
urllib3            1.26.4
woob               3.0
zipp               3.4.1

**Comment by nono-london** [comment]
j'utilise windows 10, pycharm, et depuis mon venv je lance la commande suivante:

(.venv) D:\path_to_project\doctoshotgun>doctoshotgun.py paris user_email

qui resulte en l'erreur suivante:
Traceback (most recent call last):
  File "D:\path_to_project\doctoshotgun\doctoshotgun.py", line 13, in <module>
    from dateutil.parser import parse as parse_date
ModuleNotFoundError: No module named 'dateutil'

**Comment by clemux** [comment]
Et `python doctoshotgun.py paris user_email` ?

**Comment by nono-london** [comment]
Ha oui! Désolé de vous avoir fait perdre du temps. cela fonctionne maintenant. Merci, et bon weekend.
