### ISSUE TITLE
Explications potentielles pour "found" puis "Appointment not available anymore"

### ISSUE THREAD

**Issue by zaccharieramzi** [rbignon/doctoshotgun#41]
Bonjour,

(je m'exprime en Francais car j'ai vu les autres issues ecrites comme ca mais si l'anglais est mieux je peus switcher).
Merci pour ce script qui je l'espere me sera tres utile.
Je suis en train de le faire tourner et je voudrais savoir quelles sont les explications possibles a la situation ou un slot est indique comme "found" puis est finalement indique comme  "Appointment not available anymore".

Exemple:
```
– Centre de Vaccination - Mairie du 13e... found!
  ├╴ Best slot found: Wed May 26 12:00:00 2021
  └╴ Appointment not available anymore :( unavailable_slot
– Centre de vaccination éphémère du 19 (curial)... found!
  ├╴ Best slot found: Wed May 26 12:00:00 2021
  ├╴ Second shot: Mon Jul  5 18:20:00 2021
  └╴ Appointment not available anymore :( unavailable_slot
– Centre de vaccination éphémère du 20 (Mouraud)... found!
  ├╴ Best slot found: Wed May 26 11:30:00 2021
  ├╴ Second shot: Mon Jul  5 18:20:00 2021
  └╴ Appointment not available anymore :( unavailable_slot
– Centre de vaccination éphémère du 18 (Binet)... found!
  ├╴ Best slot found: Wed May 26 12:00:00 2021
  ├╴ Second shot: Mon Jul  5 18:20:00 2021
  └╴ Appointment not available anymore :( unavailable_slot
– Centre de vaccination éphémère du 11 (Houdin)... found!
  ├╴ Best slot found: Wed May 26 12:00:00 2021
  ├╴ Second shot: Mon Jul  5 18:20:00 2021
  └╴ Appointment not available anymore :( unavailable_slot
– Centre de vaccination éphémère du 10 (Boy-Zelensky)... found!
  ├╴ Best slot found: Wed May 26 12:00:00 2021
  └╴ Appointment not available anymore :( unavailable_slot
```

Je me dis qu'il est possible d'y avoir plusieurs scripts en concurrence mais de la a ce que la situation se reproduise autant je trouve ca etrange.
Cela dit si c'est le cas, il y a peut-etre moyen d'avoir un compteur aggrege du nombre de scripts tournant en concurrence pour une certaine ville.

**Comment by rbignon** [comment]
Oui la fréquence avec laquelle ça se produit est étonnante, même si je l'ai constaté fréquemment aussi en utilisant le site manuellement.

Une explication peut être effectivement la multitude de personnes/scripts qui bouclent pour réserver un créneau, qui peut être complétée par peut-être une gestion du cache chez Doctolib qui fait apparaître des créneaux déjà réservés ?

**Comment by zaccharieramzi** [comment]
Je suis d'accord sur le point de l'utilisation manuelle.

En tout cas ce n'est pas un probleme de mon cote, je pense que c'etait ma question principale. Je ferme l'issue, merci !
