### ISSUE TITLE
Script won't work with double auth connection

### ISSUE THREAD

**Issue by tomkimsour** [rbignon/doctoshotgun#46]
# English 
As mentioned in issue #37 

When manually signing in you'd have to enter your mail address and password and then would be redirected to https://www.doctolib.fr/sessions/two-factor where you have to enter the 6 digit code you've been sent.
When this is done I suppose you get a cookie that allows the server to know if the computer is new or not.

When executed in the script, after connection it ll try to access a page that require you to be logged in. Which is not the case with double auth thus the error 401 sended by the script

# Français
Comme mentionné dans l'issue #37  

Si l'on a la double authentification voilà ce qu'il se passe

> Dans une navigation 'normale' on est redirigé vers https://www.doctolib.fr/sessions/two-factor et dans le même temps on reçoit un code à 6 chiffres à saisir sur cette page.
https://github.com/rbignon/doctoshotgun/issues/37#issuecomment-848904795

Ensuite la session peut être accéder grâce à un cookie.

Or dans le script on est directement dirigé vers une page qui demande d'être connecté et provoque l'erreur 401

**Comment by rbignon** [comment]
Bonjour,

Je ne trouve pas de moyen d'activer l'authentification forte sur mon compte Doctolib, je ne peux donc pas reproduire et donc pas patcher doctoshotgun pour le gérer.

**Comment by cvermot** [comment]
J'ai l'impression que la double authentification est réservée aux comptes doctolib professionnels non ?

Solution alternative si bien le cas : créer un compte classique ?

**Comment by rc-mendes** [comment]
L'authentification forte s'active quand on change de navigateur ou ordinateur. Je crois. A cause d'un problème de DNS dans mon réseau internet, doctolib me demandait pour toute connexion le 2af. J'ai résolu le problème sur le navigateur. Par contre, le script continue à ne pas m'autoriser la connexion.

**Comment by cvermot** [comment]
Étrange : jamais eu de demande de double authentification sur mon compte doctolib. Je viens de refaire la vérification sur un PC avec lequel je ne me suis jamais connecté à DL (pas le même OS, pas mon navigateur habituel...).

**Comment by rc-mendes** [comment]
https://community.doctolib.com/t5/id%C3%A9es/d%C3%A9sactiver-la-double-authentification/idi-p/39491

**Comment by cvermot** [comment]
J'ai l’impression que toutes les contributeurs de ce fil sont des professionnels de santé, non ?

**Comment by rc-mendes** [comment]
Alors, il y a effectivement une différence entre le Doctolib et Doctolib Pro. J'ai l'impression que sur ce fil c'est plutôt toute la communauté. Je cite la réponse de l'équipe doctolib sur le 2af : 

> Bonjour à tous et merci pour vos commentaires !
> 
> Nous mesurons le désagrément que peut constituer la double authentification parfois requise lorsque vous vous connectez à Doctolib.
> Plusieurs précisions à ce sujet :
> 
> 
> La double authentification par e-mail, SMS ou application mobile poursuit un seul objectif : garantir, autant que possible, la sécurisation des données de santé qui sont la propriété du praticien et du patient.
> 
> Cette fonctionnalité de cybersécurité standardisée est hautement recommandée pour la sécurisation de tous les systèmes d’information.
> 
> Comme l’indique @Guillou, il s’agit du seul moyen existant actuellement pour lutter efficacement contre les attaques informatiques massives de robots, de phishing ou celles ciblées contre un praticien en particulier.
> 
> La double authentification est requise qu'une seule fois par ordinateur ou smartphone utilisé.
> Elle ne vous sera donc jamais imposée deux fois pour un même appareil.
> 
> Cela étant dit, nous travaillons chaque jour à améliorer votre confort de travail et nous sommes très sensibles à vos retours.
> 
> Nos équipes étudient donc les solutions potentielles pour simplifier les modalités de connexion tout en préservant le plus haut niveau de sécurité. Et nous déploierons des évolutions dès que possible afin de mieux répondre à vos besoins.
> 
> Bonne journée !

**Comment by lionawurscht** [comment]
I managed to get this running with 2fa 23729ce081ab2881a932fff062263545827772de. It was just a quick fix and I don't habe time for a pull request but maybe this helps someone else.

**Comment by ThomasParistech** [comment]
thanks for the nice fix @lionawurscht

**Comment by alex4102** [comment]
J'ai le même problème avec la double auth :/ 401 Client Error: Unauthorized

**Comment by nicarl** [comment]
I had the same problem with an account I created for doctolib.fr some time ago.
However, I live in Germany now and tried to login with this account to doctolib.de, which worked but always required a second factor.
By creating a new account on doctolib.de I did not get the warning anymore.

**Comment by rbignon** [comment]
It may be now supported, can you test it?

**Comment by tomkimsour** [comment]
I just tested it and it works just fine !
