### ISSUE TITLE
Nouvelles règles

### ISSUE THREAD

**Issue by rbignon** [rbignon/doctoshotgun#52]
À partir du 31 mai, la prise de rendez-vous est ouverte à tout le monde sans limite en France. De fait j'ai modifié le script pour chercher par défaut le rendez-vous le plus proche dans les sept prochains jours.

Néanmoins, je ne sais pas exactement quelle serait l'attente des utilisateurs. Est-ce que par exemple il faudrait exclure le jour-même ? Est-ce qu'on rajoute une option pour définir un délai minimum ? Est-ce qu'on en profite pour rajouter des filtres supplémentaires (plage horaire) ?

**Comment by XefiNelf** [comment]
merci de la mise à jour :)

**Comment by Tylones** [comment]
> Est-ce que par exemple il faudrait exclure le jour-même ? Est-ce qu'on rajoute une option pour définir un délai minimum ?

Pour le coup je pense que il ne faut pas exclure le jour même mais plutôt mettre un délai minimum. Si les gens sont disponibles pour se faire vacciner le jour même autant qu'ils puissent chercher un rendez-vous pour le jour même.

>  Est-ce qu'on en profite pour rajouter des filtres supplémentaires (plage horaire) ?

Ca je pense aussi que c'est un bon ajout aussi, par exemple ça peut être utile pour les personnes voulant se faire vacciner en sortant du travail, ou bien avec un emploi du temps particulier. Ca évite de prendre un rendez-vous automatiquement et de constater par la suite qu'il ne convient pas et de devoir l'annuler

**Comment by cvermot** [comment]
Bonjour,

L'option date de début et date de fin (ou alors date de début + Time window) me paraît être pas mal. Ça permettrait de chercher un rdv sur une période de vacances/repos/weekend par exemple.

Après pouvoir restreindre sur une période particulière de la journée pourrait être pas mal, a définir le format pour que ça soit facilement utilisable (d'expérience ce type de format c'est vite usine à gaz si on veux gérer la plupart des cas)

**Comment by rbignon** [comment]
C'est donc maintenant fait.
