### ISSUE TITLE
Suggestion : Prise de rendez-vous pour une deuxième dose ou une troisième dose uniquement

### ISSUE THREAD

**Issue by Tylones** [rbignon/doctoshotgun#53]
Aujourd'hui le script ne permet que de réserver les deux rendez-vous (première et deuxième dose) d'un coup lorsque l'on le lance.

Serait-ce pertinent d'ajouter l'option permettant de prendre rendez vous uniquement pour la deuxième ou la troisième dose ?

Il me semble que les IDs sont les suivants : 
- Deuxième dose Pfizer : 6971
- Deuxième dose Moderna : 7004
- Troisième dose Pfizer : 8192
- Troisième dose Moderna : 8193

En tout cas merci pour ce que vous faites, ça a permis à moi et mes proches (une dizaine de personnes) de se faire vacciner rapidement !

**Comment by idjemaoune** [comment]
Je pense qu'en entrée il est intéressant d'ajouter une option ``--only-seconde`` et aussi une date a partir de laquelle on devrait faire la 2eme dose avec une option --after-date
