### ISSUE TITLE
Freeze when booking a slot

### ISSUE THREAD

**Issue by Spicers** [rbignon/doctoshotgun#58]
The script is stuck when booking a slot, please find below a print screen with debug mode.
![ubuntu_Uk0d67nIty](https://user-images.githubusercontent.com/9929215/120642829-af86d900-c475-11eb-9038-8e6355a44b91.png)

**Comment by rbignon** [comment]
Hello,

I think there is a problem during playing the useless 'ding.mp3' sound. Can you try to uninstall 'playsound' or to comment line 315 to confirm that?

**Comment by Spicers** [comment]
I commented the line 315 and it resolve the issue

**Comment by rbignon** [comment]
I removed the dependence to playsound (it is used only if already installed)
