### ISSUE TITLE
Affiliation avec plusvitemadose.fr ?

### ISSUE THREAD

**Issue by Saruspete** [rbignon/doctoshotgun#59]
Bonjour,

Il semble que le site "[plusvitemadose.fr](https://www.plusvitemadose.fr/#features)" ([archive](https://web.archive.org/web/20210604091943/https://www.plusvitemadose.fr/)) propose une offre "shotgun" pour 25€

Est-ce affilié a doctoshotgun vu la proximité du nom ?

**Comment by rbignon** [comment]
Non, il n'a jamais été dans l'objectif de doctoshotgun de gagner de l'argent, et je dois avouer que je n'adhère pas trop à leur démarche.

**Comment by Saruspete** [comment]
Oui, je me doute :) par contre je ne sais pas si c'est suffisant pour essayer d'envoyer un takedown a amazon...
Meme si y'a pas vraiment de moyen de se proteger de ce genre de comportement...

**Comment by Tylones** [comment]
Ce serait pas un copie/scam de la version vite ma dose de CovidTracker ?

Parce que l'URL de base c'est celle là https://vitemadose.covidtracker.fr et ils n'ont pas l'air de proposer de service pour réserver un créneau dessus. En plus c'est globalement la même charte graphique et tout

**Comment by rbignon** [comment]
Ah bah le lien vers archive.org était bienvenu puisque le site est maintenant down :)

**Comment by Saruspete** [comment]
Oui toujours faire une archive avant de poser une question qui fache :)

Problème est règlé. Merci à tous !

**Comment by rbignon** [comment]
https://www.reddit.com/r/france/comments/nugcsb/ama_je_suis_le_responsable_de_plusvitemadosefr/

Effectivement le gars a confirmé s'être inspiré (avoir utilisé ?) doctoshotgun. Après plus j'y pense plus son site ressemble à un scam.
