### ISSUE TITLE
Trying to use the same program in Germany, and I got a few questions

### ISSUE THREAD

**Issue by Johannes-ece** [rbignon/doctoshotgun#61]
So I dont really know how to get the motive, I thing you got it from the url like this: ref_visit_motive_ids[]=7109
with 7109 being the motive for the biontech vaccine.
So I tried it and I always get the follwing error:
Unable to find mRNA motive
Motives: Zweitimpfung Covid-19 (BioNTech-Pfizer), Erstimpfung Covid-19 (BioNTech-Pfizer), Erstimpfung Covid-19 (AstraZeneca), Zweitimpfung Covid-19 (AstraZeneca)
Zweitimpfung meaning secondshot and Erstimpfung meaning firstshot.

I would be very glad if anyone could help me!

Merci in advance :)

**Comment by SurfSealz** [comment]
Please let me know if you figure out you get this to work in Germany. I have been trying to get it to run but have not been succesful so far (not an experienced programmer).

**Comment by SurfSealz** [comment]
Change line 245: motive_id = self.page.find_motive(r'Erstimpfung.*(Pfizer|Moderna)')

**Comment by nicolaus-hee** [comment]
Check out #43

**Comment by Johannes-ece** [comment]
> Check out #43

Thank you very much! Dont know how I overlooked this.
