### ISSUE TITLE
('525 Server Error: ',)

### ISSUE THREAD

**Issue by tinom86** [rbignon/doctoshotgun#69]
Since yesterday, I get the following error after a few minutes:

An unexpected exception of type ServerError occurred. Arguments:
('525 Server Error: ',)
root@doctolib:/doctolib#

Do u have any ideas regarding this issue?

Best
Tn

**Comment by andilee111** [comment]
Same for me :(

**Comment by andilee111** [comment]
@tinom86 
Ok hotfix seems to be to replace
`return 1` with `sleep(5)` on line 619 of doctoshotgun.py

**Comment by nicarl** [comment]
I think there was a problem with cloudflare. One solution to make the script more resilient could be to catch the `ServerError`, sleep for a few seconds and continue.
I also thought some kind of messaging/notification (email?) would be nice in case the script crashes unexpectedly.

**Comment by tinom86** [comment]
> @tinom86
> Ok hotfix seems to be to replace
> `return 1` with `sleep(5)` on line 619 of doctoshotgun.py

When I replace "return 1" with "sleep(5)" in line 619, I get the error:

File "./doctoshotgun.py", line 619
    sleep(5)
           ^
TabError: inconsistent use of tabs and spaces in indentation

Best
Tn

**Comment by andilee111** [comment]
> > @tinom86
> > Ok hotfix seems to be to replace
> > `return 1` with `sleep(5)` on line 619 of doctoshotgun.py
> 
> When I replace "return 1" with "sleep(5)" in line 619, I get the error:
> 
> File "./doctoshotgun.py", line 619
> sleep(5)
> ^
> TabError: inconsistent use of tabs and spaces in indentation
> 
> Best
> Tn

The number of tabs/spaces has to be the same as for the line above `print(message)` (for me it is 16)

**Comment by tinom86** [comment]
> > > @tinom86
> > > Ok hotfix seems to be to replace
> > > `return 1` with `sleep(5)` on line 619 of doctoshotgun.py
> > 
> > 
> > When I replace "return 1" with "sleep(5)" in line 619, I get the error:
> > File "./doctoshotgun.py", line 619
> > sleep(5)
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > Best
> > Tn
> 
> The number of tabs/spaces has to be the same as for the line above `print(message)` (for me it is 16)

Thx. Solved.
