### ISSUE TITLE
Find id of other vaccines such as Astra Zeneca, HPV,...

### ISSUE THREAD

**Issue by namnhatpham1995** [rbignon/doctoshotgun#70]
Can I ask where do you find the id of vaccine? I intend to add Astra Zeneca and other vaccine into the tools but I don't know how to find their ID/Key number

**Comment by gitolicious** [comment]
Covid motive IDs can be found at https://www.doctolib.de/patient_eligibility_categories (for Germany)

AstraZeneca is `7109` for the first shot.

**Comment by namnhatpham1995** [comment]
Thank you for your help!
