### ISSUE TITLE
Are we getting too many CLI arguments?

### ISSUE THREAD

**Issue by gitolicious** [rbignon/doctoshotgun#84]
The current `master` branch scipt already has 14 CLI arguments. With the currently open PRs (#81, #83) it will be at least five more and I have plenty more in my mind. Looks like this is slowly getting out of hand. Should we switch to a config file? Any other ideas? Or just keep them coming?

**Comment by rbignon** [comment]
Hello Gitolicious,

You are right there are many arguments. However, mostly when you use doctoshotgun for someone, this is… a one shot. So command line arguments are appropriate. We can keep CLI arguments, and add another one to parse a config file :)

**Comment by rbignon** [comment]
There are currently too many opened PRs, the problem is that it complexifies the code, and some of them are incompatibles ou redundant… I have to take time to uniformise them.

**Comment by gitolicious** [comment]
In an ideal world, the script is a "one shot" (what a pun...) but in Germany currently it is really hard to find a doctor who offers appointments so you have to experiment a lot with the settings.

For PR reviews: they should be much easier and quicker when test coverage is higher as proposed in #73.

**Comment by gitolicious** [comment]
I had a quick play with a config file implementation but ultimately found it too much effort and got used to the CLI argument combination. Will close this for now until others jump in and are asking for the feature as well.
