### ISSUE TITLE
[FEATURE] Exclude entries by words

### ISSUE THREAD

**Issue by tricoos** [rbignon/doctoshotgun#87]
Whenever I search (Germany) a list of doctors will be returned, however, there are also pediatrists included in the list which will probably NOT accept me as a patient.
However, I cannot exclude them unless I manually modify the script to exclude such entries - a feature would be perfect.

Example:
"Facharztpraxis für Kinder und Jugendliche" - by just excluding entries with "Kinder" in the name it would work, this should work almost every time.

**Comment by gitolicious** [comment]
I had the same thoughts and it should be an easy addition, but pull requests are piling up currently and I didn't want to add yet another one bringing in more potential merge conflicts until @rbignon hat a chance to look through the most important ones first.

**Comment by gitolicious** [comment]
#91 should help you out.

**Comment by tricoos** [comment]
@gitolicious Thank you very much, waiting for the merge 👍

**Comment by gitolicious** [comment]
Fixed with #97 

https://github.com/rbignon/doctoshotgun/blob/477c90bf0d8a93456aed3609593223f356d810f6/README.md#L55-L56

**Comment by gitolicious** [comment]
@rbignon, can we close the issue?
