### ISSUE TITLE
[FEATURE] Log timestamp of check

### ISSUE THREAD

**Issue by PatiB87** [rbignon/doctoshotgun#88]
Could we also log the timestamp of the check?
This way I can see if it ran continuously when I put my Mac to sleep.

**Comment by gitolicious** [comment]
Would #67 fit your needs?

**Comment by gitolicious** [comment]
Should be fixed with #97 

https://github.com/rbignon/doctoshotgun/blob/7813cc1e271a7799bb14c4db31467d180e378ffa/doctoshotgun.py#L55-L60

https://github.com/rbignon/doctoshotgun/blob/7813cc1e271a7799bb14c4db31467d180e378ffa/doctoshotgun.py#L756-L757

**Comment by gitolicious** [comment]
@rbignon, can we close the issue?
