### ISSUE TITLE
520 Server Error

### ISSUE THREAD

**Issue by joevoo82** [rbignon/doctoshotgun#90]
I often get the following error message, sometimes after a few minutes, other times after hours. Afterwards the script aborts.
What does the error message mean? Connection problems are detected properly.

An unexpected exception of type ServerError occured. Arguments: ('520 Server Error:',)

Maybe the response is just truncated?

![2021-06-24_18h10_52](https://user-images.githubusercontent.com/86376240/123297081-878c1200-d517-11eb-829b-5e94773f24df.png)

**Comment by gitolicious** [comment]
This is an error sent by Cloudflare if the server response from Doctolib is empty or erroneous. It looks like this in a browser window ([Source](https://kinsta.com/de/wissensdatenbank/error-520/)):
![image](https://user-images.githubusercontent.com/26963495/123507221-90402d80-d668-11eb-9193-b5f0da5e1325.png)

I have never seen this in the script on my runs...

**Comment by gitolicious** [comment]
I actually saw this once today. Retrying the script some seconds later succeeded. I will add a meaningful error message to make the situation easier to understand.

**Comment by gitolicious** [comment]
The error message was improved with #97 and there is not much else we can do.

https://github.com/rbignon/doctoshotgun/blob/7813cc1e271a7799bb14c4db31467d180e378ffa/doctoshotgun.py#L236-L237

**Comment by gitolicious** [comment]
@rbignon, can we close the issue?
