### ISSUE TITLE
[FEATURE REQUEST] Iterate through the pages if more than 1

### ISSUE THREAD

**Issue by Yuto3S** [rbignon/doctoshotgun#92]
The current script doesn't look up on the second (or more) pages of results, but only on the first one. This means it will potentially miss appointments slots if they are from doctors in the second page.

There is a button at the bottom of the page indicating if there's a next page, which can be accessed doing something like `self.doc.xpath('//div[@class="next dl-rounded-borders dl-white-bg"]'):` and then checking if the children `<a>` exists and has a valid `href`.
![image](https://user-images.githubusercontent.com/33868494/123511029-38f98780-d67f-11eb-8bd5-400d4cf6e6f0.png)

I was not able to make this work by proceeding to that page through the regular loop, so I hacked it and updated the params in [this line](https://github.com/rbignon/doctoshotgun/blob/master/doctoshotgun.py#L236) to include `'page': 2` and running the script on a different shell.

Considering that we know if there's a next page, and I know that the script works fine on that page, I hope that someone who understands a bit more this code is able to put it together to have that as part of the regular script :)

**Comment by laucia** [comment]
relates to https://github.com/rbignon/doctoshotgun/pull/80

**Comment by Yuto3S** [comment]
Ty @laucia , closing this :)
