### ISSUE TITLE
Pull requests are piling up, @rbignon still active?

### ISSUE THREAD

**Issue by gitolicious** [rbignon/doctoshotgun#96]
Hi @rbignon, I just wanted to check in with you as pull requests are piling up without being reviewed.
If you need some help maintinig the repo, don't hesitate to give a shout to the community. I am sure there are people who are happy to help out.
Big thanks for the initial idea and your contributions so far! I learned a lot on Python web scraping through this and already got my first vaccination shot.

**Comment by rbignon** [comment]
Hi gitolicious,

Yes I am quite busy at the moment. Perhaps to help me, can you try to create a branch with all pertinent PRs merged with conflicts resolved, and a new PR for this branch?

Thank you!

**Comment by gitolicious** [comment]
Sure, I am happy to help. I have a version running locally including most of the changes so I hope it is OK if I just clean that up a little and give contributions to everyone in a single commit message. Not the perfect way but merging & resolving them one by one just to preserve a git history flooded with resolve commits would be too much work.

**Comment by rbignon** [comment]
Yes I think it is better to squash commits than having lot of merge commits :)

**Comment by gitolicious** [comment]
There it is: #97
Feel free to test it as thoroughly as you find the time for and let me know what you think. We can then close the corresponding PRs and have a look at which of the remaining ones are worth looking into afterwards.

**Comment by rbignon** [comment]
Merged!
